# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

# # 🔹 모든 lane 실행 전에 공통으로 한 번만 JDK 설정
# before_all do
#     # JDK 버전
#     java_home = `/usr/libexec/java_home -v17`.strip
#
#     ENV["JAVA_HOME"] = java_home
#     ENV["PATH"] = "#{java_home}/bin:#{ENV["PATH"]}"
#
#     UI.message("👉 fastlane 실행용 JAVA_HOME: #{ENV["JAVA_HOME"]}")
# end

  ##############################################################
  # Firebase App Distribution 배포 lane
  # 실행 명령어(디버그) : bundle exec fastlane android firebase_debug
  # 실행 명령어(릴리즈) : bundle exec fastlane android firebase_beta
  ##############################################################
  # 🔹 Debug 빌드 + Firebase 배포
    desc "Build DEBUG apk and distribute to Firebase (internal/dev testers)"
    lane :firebase_debug do
      #1) debug 빌드
      gradle(task: "clean")
      gradle(task: "assembleDebug")

      # 2) debug APK 경로 동적으로 찾기
      debug_apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
      UI.user_error!("APK 경로를 찾지 못했습니다") unless debug_apk_path

      UI.message("선택 된 DEBUG APK 경로 : #{debug_apk_path}")

      UI.message("FIREBASE_APP_ID_ANDROID_DEBUG = #{ENV['FIREBASE_APP_ID_ANDROID_DEBUG']}")
      UI.message("FIREBASE_TESTERS_DEBUG = #{ENV['FIREBASE_TESTERS_DEBUG']}")

      # 제목 설정
      version_name = sh("grep versionName app/build.gradle | awk '{print $2}'").strip.gsub('"','')
      version_code = sh("grep versionCode app/build.gradle | awk '{print $2}'").strip
      release_title = "[내부 테스트] v#{version_name} (#{version_code})"

      # 3) Firebase App Distribution 업로드
      firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID_ANDROID_DEBUG"],        # 🔹 필요하면 debug용 앱 ID 따로
        android_artifact_type: "APK",
        android_artifact_path: debug_apk_path,
        service_credentials_file: "fastlane/account-firebase-app-distribution.json", # 이 파일은 구글 클라우드 콘솔에서 다운을 받으면 됨!!

        testers: ENV["FIREBASE_TESTERS_DEBUG"],          # debug 전용 테스터
        release_notes: "DEBUG 빌드 (개발/내부 테스트용)"
      )
    end

  desc "Build and distribute to Firebase App Distribution (beta/prod testers)"
  lane :firebase_beta do
    gradle(task: "clean")
    gradle(task: "assembleRelease")

    # 2) debug APK 경로 동적으로 찾기
    apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    UI.user_error!("APK 경로를 찾지 못했습니다") unless apk_path

    UI.message("선택 된 DEBUG APK 경로 : #{apk_path}")

    UI.message("FIREBASE_APP_ID_ANDROID_DEBUG = #{ENV['FIREBASE_APP_ID_ANDROID_DEBUG']}")
    UI.message("FIREBASE_TESTERS_DEBUG = #{ENV['FIREBASE_TESTERS_DEBUG']}")

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"],
      android_artifact_type: "APK",
      android_artifact_path: apk_path,
      service_credentials_file: "fastlane/account-firebase-app-distribution.json",

      testers: ENV["FIREBASE_TESTERS"],
      release_notes: "자동 배포 테스트 빌드입니다."
    )
  end

  #####################################
  # 추후 스토어 배포가 필요할 경우에 사용 설정
  # 명령어 : bundle exec fastlane production
  #####################################
  desc "프로덕션 트랙(실제 심사용)으로 바로 업로드"
  lane :production do
    gradle(task: "clean")
    gradle(
        task: "bundle",
        build_type: "Release"
    ) # ./gradlew bundleRelease 와 동일

    aab_path = Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    UI.user_error!("ABB 경로를 찾지 못했습니다") unless aab_path

    UI.message("선택 된 aab 경로 : #{aab_path}")

    # 제목 설정
    version_name = sh("grep versionName app/build.gradle | awk '{print $2}'").strip.gsub('"','')
    version_code = sh("grep versionCode app/build.gradle | awk '{print $2}'").strip
    release_title = "v#{version_name} (#{version_code})"

    # Play Store 프로덕트 트랙에 업로드
    upload_to_play_store(
        track: "production", # 실제 프로덕트 트랙
        aab: aab_path,
        skip_upload_images: true, # 이미지/스크린샷은 콘솔에서 관리하면 true
        skip_upload_screenshots: true,
        skip_upload_changelogs: false, # changelog 올리면 true/false 선택
        release_title: release_title,
        release_status: "draft" # 심사 전/검토용이면 draft, 바로 배포면 completed
    )
  end

  #####################################
  # 추후 내부 테스트 필요할 경우에 사용 설정(aab)
  # 명령어 : bundle exec fastlane internal_test_aab
  #####################################
  desc "내부 테스트 트랙에 업로드(App Bundle)"
  lane :internal_test_aab do
    gradle(task: "clean")
    gradle(
        task: "bundle",
        build_type: "Release"
    )

    aab_path = Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    UI.user_error!("ABB 경로를 찾지 못했습니다") unless aab_path

    UI.message("선택 된 aab 경로 : #{aab_path}")

    # 제목 설정
    version_name = sh("grep versionName app/build.gradle | awk '{print $2}'").strip.gsub('"','')
    version_code = sh("grep versionCode app/build.gradle | awk '{print $2}'").strip
    release_title = "[내부 테스트] v#{version_name} (#{version_code})"

    # Play Store 내부 테스트 트랙에 업로드
    upload_to_play_store(
        track: "internal", # 내부 테스트 트랙
        aab: aab_path,
        skip_upload_images: true, # 이미지/스크린샷은 콘솔에서 관리하면 true
        skip_upload_screenshots: true,
        skip_upload_changelogs: false, # changelog 올리면 true/false 선택
        release_title: release_title,
        release_status: "completed" # internal은 그냥 completed로 바로 배포해도 됨
    )
  end

  #####################################
  # 추후 내부 테스트 필요할 경우에 사용 설정(apk)
  # 명령어 : bundle exec fastlane internal_test_apk
  #####################################
  desc "내부 테스트 트랙에 업로드(Apk)"
  lane :internal_test_apk do
      gradle(task: "clean")
      gradle(task: "assembleRelease")

      apk_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
      UI.user_error!("APK 경로를 찾지 못했습니다") unless apk_path

      UI.message("선택 된 DEBUG APK 경로 : #{apk_path}")

      # 제목 설정
      version_name = sh("grep versionName app/build.gradle | awk '{print $2}'").strip.gsub('"','')
      version_code = sh("grep versionCode app/build.gradle | awk '{print $2}'").strip
      release_title = "[내부 테스트] v#{version_name} (#{version_code})"

      # Play Store 내부 테스트 트랙에 업로드
      upload_to_play_store(
        track: "internal", # 내부 테스트 트랙
        apk: apk_path,
        skip_upload_images: true, # 이미지/스크린샷은 콘솔에서 관리하면 true
        skip_upload_screenshots: true,
        skip_upload_changelogs: false, # changelog 올리면 true/false 선택
        release_title: release_title,
        release_status: "completed" # internal은 그냥 completed로 바로 배포해도 됨
      )
  end
end
